### ISSUE TITLE
Steam Release

### ISSUE THREAD

**Issue by IceMaverick** [firefoxpdm/Rainbeau-s-Fishing#1]
Hello, I'm opening a ticket to inquire after your plans for a Steam release.
Do you plan to host the mod yourself on your own Workshop page? 
If not, I have an alternative I'd like to present. I'm part of Mlie's 1.1 continuation team (https://steamcommunity.com/sharedfiles/filedetails/?id=1541984105) as an administrator (IceMaverick). 

If you don't plan to release the mod under your own name, would you be willing to grant permission for this repository's contents to be distributed by Mlie's account and added to the linked collection? We would of course credit you for the actual updated code in the description. This mod is currently on our to-do list (https://trello.com/b/LNoylqRt/mods), but since you've already made the update, it would save us some time with so many other mods that need updating and would let Workshop users get ahold of the mod again.

Edit: While I have you, I see you've also done SS Researchable Stat Upgrades and RimDisorders. Both are on the same list and under the same situation. I'd like to request similar permissions for them at the same time.

Thank you in advance for your consideration,
The 1.1 Resurrection Team

**Comment by firefoxpdm** [comment]
Hi,

I have had far too many bad experiences with Steam, so I'm not planning to host these mods there. I also believe in the "single source of truth", and in case of these mods these are the github release pages, where I can guarantee that always the latest versions will be available. Any other hosting location would be a copy and an extra burden for me to keep up to date. Therefore I would be happy if you wish to take these burdens off of my back.

Hereby I grant you permission to use any and all of the mods located under my github project to use in any way you wish.

**Comment by IceMaverick** [comment]
Thank you for getting back to me. I'll inform the team and they'll probably be up on Steam soon in that case.
We appreciate your work and thanks for letting us use it.
